# Generated by Django 5.0.7 on 2024-07-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBiblioteca', '0002_alter_autor_nombre_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
