# Generated by Django 5.0.7 on 2024-07-26 16:29

import gestionBiblioteca.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionBiblioteca', '0004_alter_prestamo_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nac',
            field=models.DateField(validators=[gestionBiblioteca.validators.validar_fecha]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[gestionBiblioteca.validators.validar_nombre]),
        ),
    ]
